### ISSUE TITLE
Cannot find module './build/Release/shell'

### ISSUE THREAD

**Issue by olanod** [mgutz/execSync#27]
After installing with `npm install execSync` I got `Cannot find module './build/Release/shell'` error.  
I had to go into the node_modules directory and build it myself passing the flag `--python python2` to the `node-gyp rebuild` command.

**Comment by scheffield** [comment]
@julianxhokaxhiu unfortunately, this doesn't solved my problem.

Besides that, the most annoying thing about that bug is that it appears out of a sudden. Yesterday everything worked perfectly. Can everyone come up with an idea for an explanation?

**Comment by julianxhokaxhiu** [comment]
@scheffield are you sure? For me it worked also two days ago on Arch Linux where I did my new dev server (same error, same fix and now working awesome).

Try to remove your `node_modules` folder after you set the `npm config` for python :)

**Comment by n8agrin** [comment]
We resolved this a short time ago. Turned out my coworker who was hitting this problem had a rogue, custom build of make in his path. Sorry for the confusion.

**Comment by cperryk** [comment]
Also getting this issue, and I'm running Python 2.7.6. 

Running <code>node-gyp rebuild</code> doesn't work for me (command not found).

This also did not fix the issue:
```
npm config set python /usr/bin/python2.7
npm install
```

**Comment by cpinto7** [comment]
Also running in this issue. I have tried all of the suggestions above and still no luck.
Any other suggestions? Much appreciated.

**Comment by sabreena** [comment]
I am facing the same issue. Tried the above suggestions but of no help.
I am using OSX 10.9.4. Need help urgently. That will be much appreciated.

**Comment by julianxhokaxhiu** [comment]
I would suggest to use [exec-sync](https://www.npmjs.com/package/exec-sync) from now on, compatible with nodejs 0.12.x and anyway it doesn't depend on libc, python or stuff like this :)

**Comment by sabreena** [comment]
I am still getting the same error even after using sudo npm install exec-sync
The error is:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/sabreena/.nvm/v0.10.24/lib/node_modules/generator-drupal-theme/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Any other solution to it?

**Comment by julianxhokaxhiu** [comment]
Clean reinstall NPM and remove all `node_modules` folders. Then just run again `npm install` :)

**Comment by webpolis** [comment]
No solution works.

**Comment by megatolya** [comment]
No solution works to me too

**Comment by sgarbesi** [comment]
No solution here either.

**Comment by webpolis** [comment]
Only solution is switching to https://www.npmjs.com/package/exec-sync

**Comment by sgarbesi** [comment]
@webpolis Using a 3rd party library, `grunt-favicons` otherwise I would. Still looking, let you know if I find anything.

**Comment by sgarbesi** [comment]
@webpolis Wound up just forking and updating manually.

**Comment by luishdez** [comment]
These are some alternatives:
- Native for: >v0.12 https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options
- https://github.com/arturadib/shelljs

**Comment by cphyc** [comment]
It may be worth noting that you can have issues using node v0.12 instead of v0.10 for example, try downgrading it using `nvm`.

**Comment by aclowes** [comment]
Easily solved on a Mac: run `sudo make` to cause Xcode to prompt you to agree to the license terms, then run `npm install execSync` again.

**Comment by fmquaglia** [comment]
@aclowes' solution worked for me. Thanks pal! :+1:

**Comment by rvergis** [comment]
@aclowes thanks, that worked for us.

**Comment by julianxhokaxhiu** [comment]
Time to close this @mgutz ?
