### ISSUE TITLE
npm install -g angular-cli fails on execSync

### ISSUE THREAD

**Issue by kboogert** [mgutz/execSync#43]
I get the following error executing npm install-g angular-cli on OSX el-capitan
I have installed and reinstalled  the latest version of nodejs (7.0.0, fyi have also tried 6.9.1 with same results) and don't think it is a bad install.  

The err on output is 
...
136167 verbose stack Error: execSync@1.0.2 install: `node install.js`
136167 verbose stack Exit status 1
136167 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
136167 verbose stack     at emitTwo (events.js:106:13)
136167 verbose stack     at EventEmitter.emit (events.js:191:7)
136167 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
136167 verbose stack     at emitTwo (events.js:106:13)
136167 verbose stack     at ChildProcess.emit (events.js:191:7)
136167 verbose stack     at maybeClose (internal/child_process.js:877:16)
136167 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
136168 verbose pkgid execSync@1.0.2
136169 verbose cwd /Users/kboogert
136170 error Darwin 15.6.0
136171 error argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
136172 error node v7.0.0
136173 error npm  v3.10.8
136174 error code ELIFECYCLE
136175 error execSync@1.0.2 install: `node install.js`
136175 error Exit status 1
136176 error Failed at the execSync@1.0.2 install script 'node install.js'.
136176 error Make sure you have the latest version of node.js and npm installed.
136176 error If you do, this is most likely a problem with the execSync package,
136176 error not with npm itself.
136176 error Tell the author that this fails on your system:
136176 error     node install.js
136176 error You can get information on how to open an issue for this project with:
136176 error     npm bugs execSync
136176 error Or if that isn't available, you can get their info via:
136176 error     npm owner ls execSync
136176 error There is likely additional logging output above.
136177 verbose exit [ 1, true ]
...

[npm-debug.log.zip](https://github.com/mgutz/execSync/files/565298/npm-debug.log.zip)

**Comment by gjongerh** [comment]
The same result for me. Both with version 6 as 7.
[npm-debug.log.zip](https://github.com/mgutz/execSync/files/603751/npm-debug.log.zip)

**Comment by abcfy2** [comment]
Same issue here, any updates?
